{
 "title": "Foodway - Observability",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": "/comments, /culinaries, /customers, /establishments, /menu, /products, /rates, /users"
   }
  ]
 },
 "panels": [
  {
   "title": "Tempo de Atividade",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"10.0.0.243:8080\",job=\"foodway-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo de Resposta",
   "type": "stat",
   "description": "Tempo de resposta em segundos.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_ready_time_seconds{instance=\"10.0.0.243:8080\", job=\"foodway-app\", main_application_class=\"com.foodway.api.ApiApplication\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus ON",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_ready{instance=\"localhost:9090\", job=\"foodway-prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{instance=\"10.0.0.243:8080\", job=\"foodway-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Métodos GET",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"foodway-app\", method=\"GET\", instance=\"10.0.0.243:8080\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status 400",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"foodway-app\", status=~\"4.*\", uri=\"$endpoint\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status 500",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"foodway-app\", status=~\"5.*\", uri=\"$endpoint\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status 200",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count {job=\"foodway-app\", uri=\"$endpoint\", status=~\"2.*\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}