{
 "title": "Foodway - Observability",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": "/comments, /culinaries, /customers, /establishments, /menu, /products, /rates, /users"
   }
  ]
 },
 "panels": [
  {
   "title": "Prometheus Habilitado",
   "type": "stat",
   "description": "1 significa que o Prometheus está pronto para receber consultas.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_ready{instance=\"localhost:9090\", job=\"foodway-prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status 400",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"foodway-app\", status=~\"4.*\", uri=\"$endpoint\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo de Resposta API",
   "type": "stat",
   "description": "tempo medido em segundos.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_ready_time_seconds{instance=\"localhost:8080\", job=\"foodway-app\", main_application_class=\"com.foodway.api.ApiApplication\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status 200",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"foodway-app\", uri=\"$endpoint\", status=~\"2.*\"}\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Métodos GET",
   "type": "stat",
   "description": "Número total de solicitações HTTP GET recebidas.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"foodway-app\",method=\"GET\",instance=\"localhost:8080\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo de Atividade da aplicação",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Métodos POST",
   "type": "stat",
   "description": "Número total de solicitações HTTP POST recebidas.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"foodway-app\",method=\"POST\",instance=\"localhost:8080\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Consumo de CPU ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_seconds_total\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Status 500",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"foodway-app\", uri=\"$endpoint\", status=~\"5.*\"}\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}